"""Audit conformance — runs ``scitex-dev ecosystem audit-all``
on this package as a normal pytest test. Generated by
``scitex-dev ecosystem write-audit-test``. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest

# Module-level skip: if the audit binary is unavailable, every test in
# this module is skipped without that becoming an extra assertion inside
# the test body (TQ007 keeps the per-test assert count at exactly one).
if shutil.which("scitex-dev") is None:
    pytest.skip(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]",
        allow_module_level=True,
    )


def test_audit_all_clean_returns_none_for_this_package():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    # ``audit_all_for_package`` returns ``None`` on success and raises
    # ``AssertionError`` if the subprocess audit exits non-zero.
    returned = audit_all_for_package("scitex-gists")

    # Assert
    assert returned is None
